# Generated by Django 2.0.4 on 2018-04-24 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=8, max_digits=12)),
                ('date', models.DateField()),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Currency')),
            ],
        ),
        migrations.RemoveField(
            model_name='excehangerate',
            name='currency',
        ),
        migrations.DeleteModel(
            name='ExcehangeRate',
        ),
    ]
